title: rzy's blog
email: me@23ro.org
description: "rzy's blog"
baseurl: ""
url: "https://l4rzy.github.io"
github_username: l4rzy
theme: minima

description: >
  I'm a Canada based Information Security Enthusiast.

# Build settings
markdown: kramdown
permalink: pretty
future: true

kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

header_pages:
  - portfolio.md
  - about.md
