title: rzy's blog
email: ndlam96@gmail.com
description: "rzy's blog"
baseurl: ""
url: "https://l4rzy.github.io"
github_username: l4rzy
theme: minima

description: >
  I'm a Canada based Information Security Student from Vietnam who wants to be a professional Penetration Tester. 
  This blog is a way to record my learning progress, as well as to share my stuff.

# Build settings
markdown: kramdown
permalink: pretty
future: true

kramdown:
  input: GFM

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

header_pages:
  - portfolio.md
  - about.md
